USE [master]
GO

/****** Object:  Database [employee]    Script Date: 2/21/2016 3:18:23 AM ******/
CREATE DATABASE [employee]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'employee', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\employee.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'employee_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\employee_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [employee] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [employee].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [employee] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [employee] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [employee] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [employee] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [employee] SET ARITHABORT OFF 
GO

ALTER DATABASE [employee] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [employee] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [employee] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [employee] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [employee] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [employee] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [employee] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [employee] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [employee] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [employee] SET  DISABLE_BROKER 
GO

ALTER DATABASE [employee] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [employee] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [employee] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [employee] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [employee] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [employee] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [employee] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [employee] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [employee] SET  MULTI_USER 
GO

ALTER DATABASE [employee] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [employee] SET DB_CHAINING OFF 
GO

ALTER DATABASE [employee] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [employee] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [employee] SET  READ_WRITE 
GO

